### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mm-gmbd**

### CODE REVIEW

**Comment by mm-gmbd** [comment]
There are a few nuances that will need to be addressed -- 

1. notice that the `beforeOnReply` handler gets called with two arguments, the original message and the *full response payload*. The distinction here is that the `onReply` handlers get called with the message and the `data` portion of the payload. The reason for sending the full response payload to the `beforeOnReply` handler is because it is being used as middleware, and as such I didn't want to muddy the contents of the `data` portion of the payload with what I was doing with the contents of the full message, so the handler needed access to the full payload... does this make sense?

**Comment by mm-gmbd** [comment]
@ppetrosh - let me know what you think.

**Comment by mm-gmbd** [comment]
Also - this includes the change in `_onAckReceived` that only deletes the message from the `sentQueue` if there is **no** reply handler present (to allow for asynchronous reply).

**Comment by ppetrosh** [comment]
Got it, thank you @mm-gmbd! Will review and take it over from here.

**Comment by ppetrosh** [comment]
@mm-gmbd regarding the `beforeOnData` and `beforeOnReply` we are not exposing any internal structures of the message to users. Why do you need that? Why don't you use the original message payload and supply it with all the required information?

**Comment by mm-gmbd** [comment]
The reason for using the full payload is because that allows additional things to be added to the message (e.g. timestamps as I mentioned above) in the middleware without impacting the `data` portion of the payload. If I have to take care to add profiling code to every reply/response, that would require a lot of extra work on the developer, whereas exposing the full payload (and letting the user get the `data` portion themselves) allows for much more flexibility.

**Comment by ppetrosh** [comment]
Hi @mm-gmbd, I'm not sure I understand ho `onBeforeReply` with a "full" payload helps there (the full means:

```
{
    "id" : id,
    "data" : data
}
```

Say you have some `data` which is your reply and some `metadata` that you want to use. Then you send the payload:
```
{
    "id" : id,
    "data" : {
        "metadata" : metadata,
        "data" : data
    }
}
```

and access them on the other side as `payload.data` or `payload.metadata`, the same way as you suggested. So we get the same result with a less API and complexity. What am I missing?

**Comment by mm-gmbd** [comment]
Another general note -- in `beforeSend` you are already exposing the full DataMessage to the middleware, so for consistency it would make sense (with the other already-supported middlewares) to expose the full payload.

**Comment by ppetrosh** [comment]
thank you @mm-gmbd for providing the detailed example! a couple of comments:

1. In the current implementation ALL the middleware callbacks are consistent in the way they have the full message object is exposed. Please let me know which specific API call doesn't do so. Please NOTE: the `on` doesn't count as we are not sending the full message object over the wire.

2. I understand the use case, and it makes sense to me in general. And I agree that adding more APIs to the library might make this specific use case easier to implement. However a) the cost of it is an overloaded library interface which would make it hard to understand/apply for any other use case. I would be more comfortable to move forward with this proposal if we can validate it with another customer, who requests for it. But you are the only one so far... And b) that would also expand the scope of work for us to develop tests and verify all the corner use cases that the change introduces. Which might be hard to justify at this point...

3. For now I would recommend to probably extend MessageManager and add the functionality that you guys need. I'm not talking about forking the repository, but using the standard implementation just extend it the class and overwrite the methods that you need. If/when we see more demand for it, we'll incorporate your changes into the class. Does it make sense?

**Comment by mm-gmbd** [comment]
That all makes sense.

1. I didn't mean that any of the current API calls don't expose the full message object, I thought that your proposal was saying that we should only expose the `data` portion of the payload, which seems opposite from the current implementations.

2. Understood.

3. Yes, that makes sense. As the request was mostly centered around profiling messages when we were having Agent problems, I see this *mostly* as a debugging tool for now, so I'm fine with it being an extension as we are currently removed the use of these middlewares for now (but are *very* helpful when issues arise).

Can you make the extension and host it in the repository? Maybe with the stipulation that all edge cases haven't been tested and is mainly for debugging purposes at this point?

**Comment by ppetrosh** [comment]
Yes it probably makes sense to put it inside examples folder under this repository. That's going to show how you can extend the library as needed.

**Comment by betzrhodes** [comment]
Merging this with mm branch to keep reference to code. At this time there is no plan to merge this feature into a release.

**Pull request merged**
